#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $CUSTOMER_DB_USER WITH PASSWORD '$CUSTOMER_DB_PASSWORD';
    CREATE DATABASE $CUSTOMER_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $CUSTOMER_DB_NAME TO $CUSTOMER_DB_USER;
    ALTER DATABASE $CUSTOMER_DB_NAME SET TIMEZONE='Europe/Amsterdam';
    \c $CUSTOMER_DB_NAME
    ALTER SCHEMA public OWNER TO $CUSTOMER_DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $CUSTOMER_DB_USER;
EOSQL